name: âš™ï¸ CI

on:
  push:
    branches: [main]
  pull_request:

  workflow_dispatch:

jobs:
  redwood-project-ci:
    name: ğŸŒ² Redwood CI
    runs-on: ubuntu-latest
    steps:
      - name: ğŸŒ² Redwood CI
        uses: redwoodjs/project-ci-action@v0.1.1
